name: Latest Youtube Videos
on:
  schedule:
    - cron: '0 * * * *'
    workflow_dispatch

jobs:
  update-readme-with-youtube:
    name: Update this repo's whit README with latest videos on YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment-tag-name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?
          channel_id=UC7yZ6keOGsvERMp2HaEbbXQ"
